export interface FlintTemplate {
  prefix: string;
  title: string;
  description: string;
  body: string[];
}

export const templates: FlintTemplate[] = [
  {
    prefix: 'ai',
    title: 'Flint: General AI Prompt',
    description: 'General AI prompt formula',
    body: [
      'GOAL:',
      '',
      'CONTEXT:',
      '',
      'CONSTRAINTS:',
      '',
      'INPUT:',
      '',
      'EXPECTED OUTPUT:',
    ],
  },
  {
    prefix: 'dbg',
    title: 'Flint: Debug',
    description: 'Debugging prompt template',
    body: [
      'ISSUE:',
      '',
      'EXPECTED:',
      '',
      'ACTUAL:',
      '',
      'LAST WORKING STATE:',
      '',
      'ROOT CAUSE HYPOTHESES:',
      '',
      'AFFECTED FILES:',
      '',
      'ERROR LOGS:',
      '',
      'WHAT I ALREADY TESTED:',
    ],
  },
  {
    prefix: 'feat',
    title: 'Flint: Feature',
    description: 'Feature development template',
    body: [
      'GOAL:',
      '',
      'STACK:',
      '',
      'CURRENT ARCHITECTURE:',
      '',
      'CONSTRAINTS:',
      '',
      'INPUTS:',
      '',
      'EDGE CASES:',
      '',
      'EXPECTED OUTPUT:',
    ],
  },
  {
    prefix: 'review',
    title: 'Flint: Code Review',
    description: 'Code review template',
    body: [
      'Review for:',
      '- bugs',
      '- security',
      '- scalability',
      '- maintainability',
      '- edge cases',
      '- unnecessary complexity',
    ],
  },
  {
    prefix: 'arch',
    title: 'Flint: Architecture',
    description: 'Architecture planning template',
    body: [
      'SYSTEM GOAL:',
      '',
      'CURRENT LIMITATIONS:',
      '',
      'PROPOSED ARCHITECTURE:',
      '',
      'SCALABILITY REQUIREMENTS:',
      '',
      'SECURITY REQUIREMENTS:',
      '',
      'TRADE-OFFS:',
      '',
      'EXPECTED BENEFITS:',
    ],
  },
  {
    prefix: 'api',
    title: 'Flint: API Design',
    description: 'API design template',
    body: [
      'GOAL:',
      '',
      'API ENDPOINT:',
      '',
      'METHOD:',
      '',
      'REQUEST BODY:',
      '',
      'EXPECTED RESPONSE:',
      '',
      'VALIDATION RULES:',
      '',
      'AUTH REQUIREMENTS:',
      '',
      'ERROR CASES:',
    ],
  },
  {
    prefix: 'refactor',
    title: 'Flint: Refactor',
    description: 'Refactoring template',
    body: [
      'GOAL:',
      '',
      'CURRENT PROBLEMS:',
      '',
      'TECHNICAL DEBT:',
      '',
      'CONSTRAINTS:',
      '',
      'FILES INVOLVED:',
      '',
      'EXPECTED IMPROVEMENTS:',
    ],
  },
  {
    prefix: 'sec',
    title: 'Flint: Security Review',
    description: 'Security review template',
    body: [
      'Review for:',
      '- auth vulnerabilities',
      '- authorization flaws',
      '- injection risks',
      '- sensitive data exposure',
      '- insecure configurations',
      '- missing validation',
      '- rate limiting issues',
    ],
  },
  {
    prefix: 'perf',
    title: 'Flint: Performance',
    description: 'Performance optimization template',
    body: [
      'GOAL:',
      '',
      'CURRENT BOTTLENECK:',
      '',
      'METRICS:',
      '',
      'AFFECTED MODULES:',
      '',
      'ROOT CAUSE HYPOTHESES:',
      '',
      'PERFORMANCE TARGET:',
      '',
      'EXPECTED IMPROVEMENTS:',
    ],
  },
  {
    prefix: 'agent',
    title: 'Flint: AI Agent',
    description: 'AI agent workflow template',
    body: [
      'AGENT ROLE:',
      '',
      'PRIMARY OBJECTIVE:',
      '',
      'AVAILABLE TOOLS:',
      '',
      'CONSTRAINTS:',
      '',
      'DECISION RULES:',
      '',
      'FAILURE CONDITIONS:',
      '',
      'SUCCESS CRITERIA:',
    ],
  },
  {
    prefix: 'learn',
    title: 'Flint: Learning',
    description: 'Learning template',
    body: [
      'TOPIC:',
      '',
      'CURRENT UNDERSTANDING:',
      '',
      'KNOWLEDGE GAPS:',
      '',
      'REAL-WORLD APPLICATIONS:',
      '',
      'PRACTICAL EXERCISES:',
      '',
      'EXPECTED LEARNING OUTCOME:',
    ],
  },
  {
    prefix: 'decision',
    title: 'Flint: Decision',
    description: 'Decision-making template',
    body: [
      'DECISION:',
      '',
      'AVAILABLE OPTIONS:',
      '',
      'KNOWN FACTS:',
      '',
      'ASSUMPTIONS:',
      '',
      'RISKS:',
      '',
      'SECOND-ORDER EFFECTS:',
      '',
      'REVERSIBILITY:',
      '',
      'RECOMMENDED OPTION:',
    ],
  },
  {
    prefix: 'rca',
    title: 'Flint: Root Cause Analysis',
    description: 'Root cause analysis template',
    body: [
      'PROBLEM:',
      '',
      'WHEN IT STARTED:',
      '',
      'WHAT CHANGED:',
      '',
      'OBSERVED SYMPTOMS:',
      '',
      'POSSIBLE ROOT CAUSES:',
      '',
      'ELIMINATION STRATEGY:',
      '',
      'MOST LIKELY CAUSE:',
      '',
      'FIX PLAN:',
    ],
  },
  {
    prefix: 'sys',
    title: 'Flint: System Design',
    description: 'System design template',
    body: [
      'SYSTEM REQUIREMENTS:',
      '',
      'TRAFFIC ESTIMATION:',
      '',
      'DATABASE STRATEGY:',
      '',
      'API DESIGN:',
      '',
      'CACHING STRATEGY:',
      '',
      'LOAD BALANCING:',
      '',
      'FAILURE HANDLING:',
      '',
      'SCALABILITY PLAN:',
    ],
  },
  {
    prefix: 'research',
    title: 'Flint: Research',
    description: 'Research template',
    body: [
      'RESEARCH TOPIC:',
      '',
      'OBJECTIVE:',
      '',
      'KNOWN FACTS:',
      '',
      'UNKNOWNS:',
      '',
      'COMPETING HYPOTHESES:',
      '',
      'RISKS OF WRONG ASSUMPTIONS:',
      '',
      'EXPECTED INSIGHTS:',
    ],
  },
  {
    prefix: 'improve',
    title: 'Flint: Improve Prompt',
    description: 'Prompt improvement template',
    body: [
      'CURRENT PROMPT:',
      '',
      'CURRENT PROBLEMS:',
      '',
      'DESIRED IMPROVEMENTS:',
      '',
      'MISSING CONTEXT:',
      '',
      'EXPECTED PROMPT QUALITY:',
    ],
  },
  {
    prefix: 'biz',
    title: 'Flint: Business Logic',
    description: 'Business logic template',
    body: [
      'BUSINESS GOAL:',
      '',
      'USER FLOW:',
      '',
      'BUSINESS RULES:',
      '',
      'EDGE CASES:',
      '',
      'FAILURE SCENARIOS:',
      '',
      'DATA REQUIREMENTS:',
      '',
      'EXPECTED OUTPUT:',
    ],
  },
  {
    prefix: 'ui',
    title: 'Flint: UI/UX',
    description: 'UI/UX planning template',
    body: [
      'GOAL:',
      '',
      'TARGET USERS:',
      '',
      'USER PROBLEMS:',
      '',
      'RESPONSIVE REQUIREMENTS:',
      '',
      'ACCESSIBILITY REQUIREMENTS:',
      '',
      'DESIGN CONSTRAINTS:',
      '',
      'EXPECTED UI STRUCTURE:',
    ],
  },
  {
    prefix: 'deploy',
    title: 'Flint: Deployment Debug',
    description: 'Deployment debugging template',
    body: [
      'ENVIRONMENT:',
      '',
      'DEPLOYMENT TARGET:',
      '',
      'ERROR:',
      '',
      'LAST SUCCESSFUL DEPLOYMENT:',
      '',
      'INFRASTRUCTURE DETAILS:',
      '',
      'LOGS:',
      '',
      'WHAT ALREADY TESTED:',
    ],
  },
  {
    prefix: 'context',
    title: 'Flint: Context Engineering',
    description: 'Context engineering template',
    body: [
      'PROJECT TYPE:',
      '',
      'PERSISTENT CONTEXT FILES:',
      '',
      'TEMPORARY TASK CONTEXT:',
      '',
      'KNOWN CONSTRAINTS:',
      '',
      'REUSABLE PATTERNS:',
      '',
      'EXPECTED AI BEHAVIOR:',
    ],
  },
];

export const templateMap = Object.fromEntries(
  templates.map(t => [t.prefix, t])
);
